version: '3'
services:
  pool:
    dockerfile: ./poll/Dockerfile
    ports:
      - 5000:80
  redis:
    image: redis
    ports:
      - 6379:6379
  worker:
    dockerfile: ./worker/Dockerfile
  db:
    image: postgres
  result:
    dockerfile: ./result/Dockerfile
    ports:
      - 5001:80
