version: "3"
services:
  pool:
    build:
      context: ./
      dockerfile: ./poll/Dockerfile
    container_name: poll
    ports:
      - 5000:80
  redis:
    image: redis
    ports:
      - 6379:6379
  worker:
    build:
      context: ./
      dockerfile: ./worker/Dockerfile
    container_name: worker
    depends_on:
      - redis
  db:
    image: postgres
  result:
    build: 
      context: ./
      dockerfile: ./result/Dockerfile
    container_name: result
    ports:
      - 5001:80
    depends_on:
      - db
